apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geotracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geotracker
    spec:
      containers:
        - name: geotracker
          image: knpatil/geotracker:latest
          ports:
            - containerPort: 8080
